[tool.black]
line-length = 88
target-version = ["py310"]
extend-exclude = '''
(
  ^/data/
  | ^/downloads/
  | ^/notebooks/
)
'''

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
exclude = ["data", "downloads", "notebooks"]
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["T201"]
