name: atmoseer
channels:
  - conda-forge
dependencies:
  - python=3.10
  - folium
  - gdal=3.7
  - geopandas
  - joblib
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pillow
  - pyarrow
  - pyproj
  - seaborn
  - scikit-learn
  - xarray
  - rasterio
  - s3fs
  - scipy
  - metpy
  - requests
  - ipykernel
  - pip
  - tqdm
  - pip:
    - boto3
    - torchvision



